### PR TITLE
fix: Changed min value to 1500 as this seems to be a valid value

### LINKED ISSUE #5: Invalid Temperature Range on GetState
Managed to get my lights into a temperature range outside of what is setup here.

Any effects on trying to change it respond back as failure as SetTemperatureAsync calls GetState first then tries to parse that before issuing the new values.

Minimum Value change 1500

### PR DESCRIPTION
**Pull request by JasonPulse**
closes #5

### CODE REVIEW

**Comment by OllieDay** [comment]
Thank you once again. I can see there are some new products that support kelvin range down to 1,500 now!

**Comment by JasonPulse** [comment]
No Problem.

 I have not figured it out yet but I would love to add a power command to some of the set commands.  
 
I'm running into an issue where the bulbs ignore some commands and I think its because its receiving to many commands.  For example a set color would be. Power on, Set color, while internally i think the library is doing get status for some other parameters needed.

Does something like that seem "easy"?  I'm looking to reduce the amount of commands sent to the bulbs in order to fix the amount of commands getting ignored.

**Comment by OllieDay** [comment]
> I have not figured it out yet but I would love to add a power command to some of the set commands.
> 
> I'm running into an issue where the bulbs ignore some commands and I think its because its receiving to many commands. For example a set color would be. Power on, Set color, while internally i think the library is doing get status for some other parameters needed.
> 
> Does something like that seem "easy"? I'm looking to reduce the amount of commands sent to the bulbs in order to fix the amount of commands getting ignored.

From memory I don't think it's possible to set the off/on state in the same command as colour/temperature/brightness. The [docs](https://github.com/LIFX/lifx-protocol-docs/blob/master/messages/light.md) show them as separate commands.

I think you could try making the `SetPropertiesAsync` method public and use that as it would mean the request made to get the current state is bypassed, but that'd mean you'll have to set colour, brightness, and temperature all together, and still need a separate subsequent request for off/on.

https://github.com/OllieDay/Lifx/blob/2c0c3abab33fe7497d31d4ba7a0369213fa099da/Lifx/Light.cs#L191-L202

Another thing that *might* work is to try setting `ackRequired` to `false` for all of the set commands and see if that makes a difference.

https://github.com/OllieDay/Lifx/blob/2c0c3abab33fe7497d31d4ba7a0369213fa099da/Lifx/Communication/Requests/RequestFactory.cs#L87

There's also the [HTTP API](https://api.developer.lifx.com/reference/introduction) which might be worth looking at although obviously there are pros and cons of using that over the LAN Protocol.

**Comment by JasonPulse** [comment]
Gotcha. I think I will just go with my plan of using brightness 0 asan off state. That seems to be functioning better in my testing

Thanks for giving me options

**Pull request merged**
